example/App.tsx, example/ios/Podfile.lock, example/ios/moneykitconnectreactnativeexample.xcodeproj/project.pbxproj, example/ios/moneykitconnectreactnativeexample.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, example/package-lock.json, example/package.json, ios/Connect.podspec, ios/ConnectModule.swift, package.json, src/index.ts
We were unable to replicate the issues encountered by a user during their testing however we have made this speculative change to how the event emitter is initialised in the JS layer between the native SDK and the users application. We believe the pervious declaration may have led to an emitter persisting across launches and possibly causing issues.
Also bumped the iOS SDK to 1.1.9 which has refined public events.
=> Speculative fix for event emitter crash

android/src/main/java/expo/modules/moneykitconnectreactnativesource/ConnectModule.kt, example/App.tsx, example/ios/Podfile.lock, ios/Connect.podspec, ios/ConnectModule.swift, package-lock.json, src/index.ts
Previously the SDK had two functions to start a link:
- `presentInstitutionSelectionFlow`
- `presentLinkFlow`
This followed the native iOS SDK as it has levels of customisation that can be applied to the institution selection flow. These customisations are not available in the react native SDK therefore we have unified the API to be a single entry point to keep things simple.
We have also re-worked the event emitter code in order to try and prevent any crashes.
=> Launch SDK with single entry point

example/ios/Podfile.lock, ios/Connect.podspec, ios/ConnectModule.swift, package.json
This updates to the latest MoneyKit Connect IOS Framework which has a fix for a relinking crash.
=> Update MoneyKit Connect SDK version

example/ios/Podfile.lock, ios/Connect.podspec, package.json
This bumps the React Native SDK to version 1.1.0
This includes the latest native [iOS SDK release](https://github.com/moneykit/moneykit-ios/releases/tag/1.2.0). There were no breaking changes in this release so no code updates required.
=> Update to latest MoneyKit SDK 1.2.0

example/ios/Podfile.lock, ios/Connect.podspec, package.json
This bumps the React Native SDK to version 1.2.0
This includes the latest native [iOS SDK release](https://github.com/moneykit/moneykit-ios/releases/tag/1.2.1). There were no breaking changes in this release so no code updates required.
=> Update MoneyKit iOS SDK to 1.2.1

example/ios/Podfile.lock, ios/Connect.podspec, package.json
This bumps the React Native SDK to version 1.2.1
This includes the latest native [iOS SDK release](https://github.com/moneykit/moneykit-ios/releases/tag/1.2.2). There were no breaking changes in this release so no code updates required.
=> Update MoneyKit SDK to 1.2.2

example/ios/Podfile.lock, ios/Connect.podspec, ios/ConnectModule.swift, package.json
This bumps the React Native SDK to version 1.2.2
This includes the latest [iOS SDK release](https://github.com/moneykit/moneykit-ios/releases/tag/1.3.0). There were no breaking changes in this release, we were able to remove the conditional checks on the link session token as the latest iOS SDK has merged its flow entry point.
=> Update MoneyKit SDK to 1.3.0

android/build.gradle, android/src/main/java/expo/modules/moneykitconnectreactnativesource/ConnectModule.kt, example/ios/Podfile.lock, ios/Connect.podspec, package.json
This bumps the React Native SDK to version 1.3.0
This includes the latest [iOS SDK release](https://github.com/moneykit/moneykit-ios/releases/tag/1.3.1). There were no breaking changes in this release.
This also includes the latest [Android SDK release](https://central.sonatype.com/artifact/com.moneykit/connect/0.0.5/versions). There were no breaking changes in this release.
=> Update MoneyKit SDKs

example/ios/Podfile, example/ios/Podfile.lock, example/ios/moneykitconnectreactnativeexample.xcodeproj/project.pbxproj, ios/Connect.podspec, package-lock.json, package.json
This PR makes a few updates:
- Updates the iOS SDK to the [latest release](https://github.com/moneykit/moneykit-ios/releases/tag/1.5.0).
- Update the Expo SDK to the [latest version](https://www.npmjs.com/package/expo/v/50.0.7)
- Removes the dependency on the `expo-modules-core` which should resolve [dependency conflicts](https://github.com/moneykit/moneykit-react-native/issues/22)
=> Update MoneyKit iOS SDK to 1.5.0

example/ios/Podfile.lock, ios/Connect.podspec, package.json
This bumps the React Native SDK to version 1.5.1
This includes the latest [iOS SDK release](https://github.com/moneykit/moneykit-ios/releases/tag/1.5.2). There were no breaking changes in this release.
=> Update MoneyKit SDK to 1.5.2

example/ios/Podfile.lock, ios/Connect.podspec, package.json
This bumps the React Native SDK to version 1.6.0
This includes the latest [iOS SDK release](https://github.com/moneykit/moneykit-ios/releases/tag/1.6.0). There were no breaking changes in this release.
=> Update MoneyKit iOS to 1.6.0

android/build.gradle, package.json
Expo v50 had some required changes for Android configs in Expo modules:
> **If you maintain any Expo Modules:**
> - For Android: update your library build.gradle to match the changes in [this diff](https://gist.github.com/brentvatne/61cd1a938fb4ba8869bc490647aa52e8). You may also now remove the JVM target version configuration, [as explained in this FYI page](https://expo.fyi/expo-modules-gradle8-migration#error-task-current-target-is-17-and-compilereleasekotlin-task-current-target-is-11-jvm-target-compatibility-should-be-set-to-the-same-java-version).
https://expo.dev/changelog/2024/01-18-sdk-50
This PR implements these changes and updates the module version to 1.7.0.
=> Increase version to 1.7.0: Android fixes for expo 50

example/ios/Podfile.lock, ios/Connect.podspec, package.json
This bumps the React Native SDK to version 1.8.0
This includes the latest [iOS SDK release](https://github.com/moneykit/moneykit-ios/releases/tag/1.6.1). There were no breaking changes in this release.
=> Update MoneyKit iOS SDK to 1.6.1

example/ios/Podfile.lock, ios/Connect.podspec, package.json
This bumps the React Native SDK to version 1.10.1
This includes the latest [iOS SDK release](https://github.com/moneykit/moneykit-ios/releases/tag/1.7.1). There were no breaking changes in this release.
=> Update iOS SDK to 1.7.1

android/build.gradle, package.json
This bumps the React Native SDK to version 1.11.0 and also updates to the [latest Android SDK](https://central.sonatype.com/artifact/com.moneykit/connect/0.1.0/versions)
=> Update Android SDK to 0.1.0

android/src/main/java/expo/modules/moneykitconnectreactnativesource/ConnectModule.kt, package.json
This PR properly formats token in the onSuccess event payload. 
This is a **breaking change** so we will need to release a version with bigger bump probably 1.2.0.
Now the approach is unified for both platforms where the `token` field contains `value` field.
=> feat: properly format token in payload

ios/Connect.podspec, package.json
This points the React Native SDK to the latest release of the [MoneyKit iOS SDK](https://github.com/moneykit/moneykit-ios/releases/tag/1.9.1)
=> Bump iOS SDK to 1.9.1

ios/Connect.podspec, package.json
This points the React Native SDK to the latest release of the [MoneyKit iOS SDK](https://github.com/moneykit/moneykit-ios/releases/tag/1.9.2)
=> Bump iOS SDK to 1.9.2

ios/Connect.podspec, package.json
This points the React Native SDK to the latest release of the [MoneyKit iOS SDK](https://github.com/moneykit/moneykit-ios/releases/tag/1.9.3)
=> Bump iOS SDK to 1.9.3

ios/Connect.podspec, package.json, src/Connect.types.ts
This points the React Native SDK to the latest release of the [MoneyKit iOS SDK](https://github.com/moneykit/moneykit-ios/releases/tag/1.9.4)
=> Bump iOS SDK to 1.9.4

android/build.gradle, package-lock.json, package.json
Update Android targetSdkVersion to 35, update MoneyKit Connect SDK dependency to latest 0.4.2.
=> S15 201 mandatory android and moneykit sdk bump
